<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fraisr
 * @package    Fraisr_Connect
 * @copyright  Copyright (c) 2013 das MedienKombinat Gmbh <kontakt@das-medienkombinat.de>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     André Herrn <andre.herrn@das-medienkombinat.de>
 */
?>

<?php if ($this->productIsActiveInFraisr()): ?>
    <iframe
        src="<?php echo $this->getIframeUrl(); ?>"
        style="border:0;"
        name="fraisr_donation_label"
        class="fraisr_donation_label_top">
    </iframe>
<?php endif; ?>