<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fraisr
 * @package    Fraisr_Connect
 * @copyright  Copyright (c) 2013 das MedienKombinat Gmbh <kontakt@das-medienkombinat.de>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     André Herrn <andre.herrn@das-medienkombinat.de>
 */
?>

<script
    type="text/javascript"
    src="https://s3-eu-west-1.amazonaws.com/fraisr-com/assets/magento/fraisr.js">
</script>

<link
    rel="stylesheet"
    type="text/css"
    href="https://s3-eu-west-1.amazonaws.com/fraisr-com/assets/magento/fraisr.css"
    media="all" />