<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fraisr
 * @package    Fraisr_Connect
 * @copyright  Copyright (c) 2013 das MedienKombinat Gmbh <kontakt@das-medienkombinat.de>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     André Herrn <andre.herrn@das-medienkombinat.de>
 */
?>
<table cellspacing="0" class="switcher" width="100%" class="form-list">
    <col width="200px" />
    <col />
    <thead>
        <tr>
            <th colspan="2">
                <?php echo $this->__('Support information'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $this->__('Extension Version'); ?></td>
            <td><?php echo $this->getExtensionVersion(); ?></td>
        </tr>
        <tr>
            <td class=label><?php echo $this->__('Support contact Fraisr:'); ?></td>
            <?php 
                $bodyInfo = array(
                    '',
                    '====',
                    $this->__('Magento version: ') . $this->getMageVersion(),
                    $this->__('Extension version: ') . $this->getExtensionVersion(),
                    $this->__('Shop URL: ') . Mage::getBaseUrl()
                );
            ?>
            <td>
                <a href="mailto:<?php echo $this->getSupportEmail(); ?>?body=<?php echo rawurlencode(implode("\n", $bodyInfo)) ?>">
                    <?php echo $this->getSupportEmail() ?>
                </a>
        </td>
        </tr>
    </tbody>
</table>

